package org.gbif.geocode.ws.model;

/**
 * An SVG shape generated by PostGIS, for use when generating the cache bitmaps.
 */
public class SvgShape {

  String id;
  String shape;

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public String getShape() {
    return shape;
  }

  public void setShape(String shape) {
    this.shape = shape;
  }
}
